#!/bin/bash
set -e -o pipefail

ytimeq ()
{
	TIME="TimeQ: elapsed %E (ring3 %U, ring0 %S, CPU %P)." "$(which time)" "$@"
}

Main ()
{
	printf "Building...\n{\n"
	local Builder_sFolder="230611_MyProjectBuilder_PerlEdition"
	
	IMAGINARYPLAYER_STRING_VIEW_BOOST="${IMAGINARYPLAYER_STRING_VIEW_BOOST:-0}" \
	IMAGINARYPLAYER_OPTIONAL_BOOST="${IMAGINARYPLAYER_OPTIONAL_BOOST:-0}" \
	BOOST_ROOT="${BOOST_ROOT:-}" \
	CXX="${CXX:-g++}" \
	CXXFLAGS="${CXXFLAGS} -pthread -std=gnu++17 -DIMAGINARYPLAYER_STRING_VIEW_BOOST=${IMAGINARYPLAYER_STRING_VIEW_BOOST} -DIMAGINARYPLAYER_OPTIONAL_BOOST=${IMAGINARYPLAYER_OPTIONAL_BOOST}" \
	LDFLAGS="${LDFLAGS} -pthread" \
	ytimeq perl -I "${Builder_sFolder}/" -I "${Builder_sFolder}/221227_PerlLib_02h/" "${Builder_sFolder}/Go.pl" "$@"
	
	printf "}\n\n"
}

Main "$@"
