= [2023-06-11] ImaginaryPlayer
:docinfo: shared
:date:    2023-06-11
:toc:     macro

== README

Example of Worker Threads and Message Passing (as opposed to lower-level synchronization).



== Contact/support:

adder_2003@yahoo.com -- Thank you so !! (-:



== Building the Project

Bash script for the impatient:

```
set -o pipefail; readarray -t as < <(ls *.cpp | grep -Piv "_UT"); printf "%s\n" "${as[@]}"; xtimeq g++ -pthread -std="gnu++17" -g "${as[@]}" -o "Main" 2>&1 | tee "_go"
```

Alternatively, we can use the custom build system (with some hardcoding, currently):

```
./Go 2>&1 | tee "_go"
```

This is going to:

* transform `README.adoc` in `README.html` (if the `asciidoctor` Ruby gem is available);
* compile each `.cpp` file;
* gather together most object files into an archive (a static library);
* link the shared library and the `Main.o` object file into the `Main` executable;
* link the shared library and each `*_UT.o` object file into a `*_UT` executable (a unittest);
* run each unittest.

All files generated by compilation, archiving, and linking are placed in the `"_Build/"` sub-folder.



== Running the Project

When we run `"_Build/Main"`, the Player is going to be initialized with two imaginary songs,
one of length 3 seconds and the other of length 6 seconds, and is going to be in the "Playing" state.

The user can enter commands after the `"[Main] >"` prompt (on the next line).

Because output from the Player (prefixed by `"[Play]"`) is mixed with output from the Main thread (prefixed by `"[Main]"`),
the prompt might get lost in the "noise". However, the user should not be discouraged by this and just type his/her commands.
The `"help"` command is going to show a list of available commands. Commands are case-insensitive.

=== User commands

[%autowidth]
[cols="1,1"]
|===
|Command (regex)|Effect

|`Help`
|Displays help for the user.

|`Exit`
|Gracefully stops the process.

|`Show\|ShowPlayer`
|Displays debugging information about the Player.

|`ShowSongs`
|Displays songs.

|`Verb <level>`
|Sets the verbosity level for the Player (`0` or `1`). Initial value: `0`.

|`AddSong \(<song-description>\)`
|Adds the specified song to the queue.

|`(Remove\|RemoveSong) <song-index>`
|Removes the specified song from the queue. The index is the 0-based number displayed by `ShowSongs`.

|`RemoveDups`
|Removes duplicate songs from the queue.

|`Play\|Pause`
|Toggles the "playing" state.

|`Sleep <number-of-milliseconds>`
|Puts the main thread to sleep => commands are not going to be processed for the specified duration. (This command is useful for functional tests.)

|`Prev\|Next`
|Jumps to the previous song or to the next song (in history).

|`Repeat (0\|1)`
|Toggles the "repeat" mode.

|`Random (0\|1)`
|Toggles the "random" mode.
|===

Example of `<song-description>`:

```
(artist "Madonna", song "Frozen", codec "MP3", length 329000)
```


== Functional test

By running `"./Test"`, a functional test (in `"./Test.pl"`) is going to be executed.
It feeds the input in the script to the `"_Build/Main"` program:

```
Sleep 10000
AddSong (length 1000)
Sleep 100
Prev
Sleep 100
Prev
Sleep 100
Prev
Sleep 100
Next
Sleep 100
Next
Sleep 100
Next
Sleep 2000
Exit
```



== Coding style and naming conventions

Classes (and class templates) and functions (and function templates) are named `LikeThis`.

Variables are named `likeThis`.

Member variables are named `_likeThis`.

Where possible, there is a whitespace between text and opening parenthesis (just like in normal text (for example, in this very line you are reading now)).



== Naming of variables

Hungarian Notation is used quite often, as learnt a long time from the beloved "Programming Windows 95" book by Charles Petzold.
In Hungarian Notation, each name is prefixed with a few lowercase characters which identify the type of the variable.

Examples:

* `contSongs`: A container of `Song` objects.
* `sInput`: A string containing the input (to the current piece of code, e.g. function etc.).

Advantages:

* we can see the type of the variable without looking up its declaration;
* it becomes easy to produce names (based simply on the type).

Disadvantages:

* it takes a little getting used to;
* with generic programming (templates), it may sometimes be difficult to know the type of a variable.

Actually, a simplified version of the Hungarian Notation is used, which does not stress too much the accuracy of the naming prefix.
For examples, integrals are often prefixed with just `i` or `n`, irrespective of the exact type of the integral (i.e. `int` or `unsigned int` or `int64_t` or `uint64_t`).

Reference variables are named just like the object variables, without an additional prefix for "reference".
Pointer variables are names similarly to the pointees, with the addition of a `p` prefix, e.g. `pContSongs` or `pcontSongs` is a "pointer to container of `Song` objects".

Often-used prefixes:

[%autowidth]
[cols="1,1"]
|===
|Prefix|Meaning

|`b`
|`bool` or (rarely if ever) byte (e.g. `unsigned char` etc.).

|`i\|n`
|Integral. `i` often denotes an index, `n` often denotes a count (a number of elements etc.).

|`c`
| Character (`char`, `wchar_t` etc.).

|`s`
|String (`std::string`, `std::wstring` etc.).

|`psz`
|Pointer to NUL-terminated array of characters ("pointer to zero-terminated string").

|`sv\|s`
|String view (`std::string_view` etc.). Often, when the distinction between `std::string` and `std::string_view` is merely related to optimization, we use `s` for `string_view`\'s too.

|`cont`
|Container.

|`iter`
|Iterator.

|`opt`
|`std::optional <...>`

|`p`
|Pointer.

|`sp`
|`std::shared_ptr <...>`. Note that when the distinction between `std::shared_ptr <...>`\'s and raw pointer is not important, we might use `p` for `std::shared_ptr <...>`\'s too.

|`rv`
|Return value.

|`value`
|Variable holding the argument of a setter function.

|`song`
|`Song` object. This convention is used in many places, e.g. `worker` prefix for `Worker` objects etc.

|`t`
|`TimePoint` object.

|`dt`
|`Duration` object.

|`cc`
|Count of characters.

|`cc_dt`
|Count of characters used for displaying durations (as argument to `std::setw`).

|===



== `std` vs `boost`

With a modern version of G++, Boost libraries are not needed.

But on the particular home computer used to develop the project, I have g++-5.4.
It has some support for C++17, but without `std::optional <...>` and without `std::basic_string_view <...>` (and without structured bindings too).
Therefore, during building, we allow a choice between the Boost versions and the Standard Library versions for these libraries.

Please see `"string_view.hpp"` and `"optional.hpp"`.

The controlling macros are `IMAGINARYPLAYER_STRING_VIEW_BOOST` and `IMAGINARYPLAYER_OPTIONAL_BOOST`.
They may be predefined by the user (e.g. via the `CXXFLAGS` envvar when invoking the `./Go` build script).
A zero value means that the Standard Library version is to be used.
A non-zero value means that the Boost version is to be used.

The resulting identifiers are placed in the `lyb` namespace, so our code uses `lyb::optional <...>` instead of `std::optional <...>` etc.

(By default, the Standard Library versions are used. However, the `Go.bat` script -- which is meant primarily for my home computer -- sets these variables to 1 before invoking the `./Go` script.)



== Higher-level conventions (idioms and design patterns)

For classes with virtual functions (classes within hierarchies), the Template design pattern is used extensively.
Specifically, the important sub-case called the Non-Virtual Interface design pattern is used.
It is described in Herb Sutter's "Virtuality" article (2001) (http://www.gotw.ca/publications/mill18.htm).

Shortly, we avoid public virtual functions (just like the Standard Library avoids them) -- except (for technical reasons) for the destructor.
The non-public virtual functions often have a `Do_` prefix in their names.
The public non-virtual (wrapper) functions often invoke one or more non-public virtual functions while adding instrumentation
(testing of pre-conditions, testing of post-conditions, pre-logging, post-logging, decision making etc.).

The Strategy design pattern is also used when appropriately, e.g. for `Worker` objects which are (optionally) configured with `WorkerImpl`-derived objects.



== And what about Named Arguments for Function Calls ?

Languages such as Python allow the caller to specify the name for each argument (instead of relying on the position of the argument in the argument list).

In the "The Design and Evolution of C++" book (1994), Bjarne Stroustrup describes how this can be implemented in C++
(the reason for refusing similar proposals for C++). Please see Section 6.5.1.1 ("Alternatives to Keyword Arguments") on page 156 (in the "Standardization" chapter).

This technique relies on the "setter" member functions returning reference to (non-const) `*this`.
IMO, this exploits a minor loophole in the language: we cannot bind an lvalue-reference-to-non-const to a temporary object (i.e. to a prvalue),
but we can call non-const member functions for such a temporary object.
So we cannot write `v.swap (std::vector <Widget> ())`, but we can write `std::vector <Widget> ().swap (v);`.

In this project, we use a modern implementation of that technique (personal invention, or possibly re-invention -- if someone else has used this before me),
which relies on C++11 `auto` for even greater convenience
(and on C++11 move semantics for efficiency even in the absence of copy elision)
(and on C++17 guaranteed copy elision).

For example, in the `Song_UT.cpp` unittest, we can see this code:

```
const auto song = Song {}.SetArtistName ("Madonna").SetSongName ("Frozen").SetCodecName ("MP3").SetLength (std::chrono::minutes {5} + std::chrono::seconds {29});
```

This is safer and more expressive and (IMO) more convenient than:

```
const Song song ("Madonna", "Frozen", "MP3", std::chrono::minutes {5} + std::chrono::seconds {29});
```

(especially given the fact that the first three arguments have the same type => no compiler warning in case of mismatch).





== Implementation of the Project

We have three threads:

* the Main thread;
* two Worker threads: the Player thread and the Logger thread.

The Logger thread is responsible for logging (`std::cout` output).
Both the Main thread and the Player thread issue "logging" commands to the Logger thread.
That way, we do not need to lock a mutex while emitting output to `std::cout`,
which would have broken the "Avoid calling unknown code while inside a critical section" rule
(described in Herb Sutter's 2007 article: https://herbsutter.com/2007/11/06/effective-concurrency-avoid-calling-unknown-code-while-inside-a-critical-section/).

For similar purposes, all interaction with the `Player` object is done on the Player thread.

The Main thread is responsible for reading and lexing and parsing user input (the commands and their arguments)
and for enqueuing commands for the Player thread.

Log messages emitted via the Logger thread are prefixed with either `"[Main]"` or `"[Play]"`,
in order to show which thread which has demanded the logging.
Log messages are also prefixed with the timestamp (monotonic time elapsed since process start).

Example:

```
[  3000] [Play] GetTimeToWait
{
        We have finished playing (artist "", song "Demo Song of 3 seconds", codec "", length 3000).
        We have started  playing (artist "", song "Demo Song of 6 seconds", codec "", length 6000).
}
[  9000] [Play] GetTimeToWait
{
        We have finished playing (artist "", song "Demo Song of 6 seconds", codec "", length 6000).
}
exit
[ 11280] [Main] Processing command line: `exit`.
Buh-bye, Imaginary World !
```



== `Worker` objects

A `Worker` object implements a message queue for a worker thread.

```
class Worker
{
...
 public:
	// [2023-06-17] Class mechanics:
	//   We have a `unique_ptr <IncompleteType>` member variable => we need a destructor which sees the complete type.
	//   We also have a `mutex` and a `condition_variable`       => no move operations.
	~Worker
	();
	
	explicit
	Worker
	(std::unique_ptr <WorkerImpl> pImpl = nullptr);
	
	static
	void
	ThreadFn
	(const std::shared_ptr <Worker> &spWorker);
	
	void
	AddWorkItem
	(const SPWorkItem &spWorkItem);
};
```

The `AddWorkItem` non-static member function can be called on any thread and adds a work item (a command to execute) to the queue:

```
void
Worker::AddWorkItem
(const std::shared_ptr <WorkItem> &spWorkItem)
{
	std::unique_lock <std::mutex> lock (_mtx);
	_contspWorkItems.push_back (spWorkItem);
	lock.unlock ();
	_cv.notify_all ();
}
```

The `ThreadFn` static member function is the main function of the worker thread.
It "pumps the message loop" by waiting on the condvar to be signaled (via `AddWorkItem`),
actually waiting for the container of work items to contain at least one command to execute.

Then, after having woken up from the waiting, with the mutex still locked, it extracts the work items in a local container (by moving/swapping them and/or by moving/swapping the container => no unknown code is called with the mutex locked).

Then it unlocks the mutex and starts executing the work items.

An empty work item is an indication that the loop should be stopped.
Even more, each work item may return a value with a bit set in order to indicate that the loop should be stopped.



== `ScopedWorkerThread`

A `ScopedWorkerThread` object is given a shared pointer to a `Worker` object.
Its constructor stores a copy of the shared pointer to the `Worker` object and spawns a thread running `Worker::ThreadFn`.
Its destructor adds an empty work item to the `Worker` object and then joins the worker thread.

(A `ScopedWorkerThread` object is similar to a `boost::scoped_thread <...>` object or to an `std::jthread` object.)

Examples of usage: initialization on the Main thread:

```
const auto Logger_spWorker {std::make_shared <Worker> ()};
const auto Logger_jthread {ScopedWorkerThread {Logger_spWorker}};

const auto t0 {Now ()};
const auto logcontext     {LogContext {t0}.SetSPWorker (Logger_spWorker).SetThreadName ("Main")};
const auto logcontextPlay {LogContext {t0}.SetSPWorker (Logger_spWorker).SetThreadName ("Play")};

const auto spPlayer {std::make_shared <Player> (logcontextPlay)};
const auto Player_spWorker {std::make_shared <Worker> (std::make_unique <WorkerImpl_Player> (spPlayer))};
const auto Player_jthread {ScopedWorkerThread {Player_spWorker}};

ComposeAndLog (logcontext, [] (std::ostream &os) { os << "Surprise !\n"; });
```



== `WorkerImpl`-derived objects

A `Worker` object is optionally configured with a `WorkerImpl`-derived object (passed via `unique_ptr` to the `Worker`'s constructor).
This `WorkerImpl`-derived object specifies:

* a timeout for the condvar waiting (returned by a callback invoked before each waiting);
* a callback to execute before processing the work items detected in the queue;
* a callback to execute on condvar waiting timeout (currently not used).

This allows a common skeleton for the message pumping loop,
but also allows differences between the Logger thread and the Player thread.

Specifically, the Player thread has to wake up from the condvar waiting not just when receiving a work item (a command to execute),
but also when the timeout expires (when the current song has finished playing).
Therefore, the Player `Worker` object is configured with a `WorkerImpl_Player` object.

Currently, the callbacks in the `WorkerImpl_Player` object just delegate work to similar functions in an aggregated (via `shared_ptr`) `Player` object.
This allows the `Player` object to be shared between the Main thread and the Player thread.
(Otherwise, the `WorkerImpl_Player` object would have needed to be shared, and possibly its exact type would have needed to be recovered by downcasting.)

Example of how the shared `Player` object is used in the Main thread:

```
...
else
if (Command_sTextLo == "pause")
{
	Player_spWorker->AddWorkItem
	(
		std::make_shared <Worker::WorkItem>
		(
			[=] () { return spPlayer->Play (arg, false); }
		)
	);
}
else
if (Command_sTextLo == "play")
{
	Player_spWorker->AddWorkItem
	(
		std::make_shared <Worker::WorkItem>
		(
			[=] () { return spPlayer->Play (arg, true); }
		)
	);
}
else
...
```



== `WorkItem::Arg` argument for virtual functions and their wrappers

What if, in the future, we decide we need to add a certain argument to one of the virtual functions ?

Then we are going to have to modify the source code not just for the base class, but for all implementations (i.e. for all of the derived classes).

In order to make our life easy, we are going to pass (to these virtual functions) an argument of type `Arg` (by reference-to-const),
so that we can add more variables inside that `Arg` object.

Currently, a `WorkItem::Arg` object only holds the current timestamp (the "now" moment).



== `WorkItem`s vs logging: capturing by value vs capturing by reference

In the lambdas for `Worker::AddWorkItem`, we capture by value, because the command is going to be executed on another thread.

(We have seen an example at the end of the previous section.)

In the lambdas for logging, we capture by reference, because the composing of the log message runs on the caller thread
(then the resulting message is passed to the other thread by the `ComposeAndLog` infrastructure).

Example:

```
ComposeAndLog (logcontext, [&] (std::ostream &os) { os << "\n" << osHelp.str (); });
```

The `std::ostream &os` is a reference to an `std::ostringstream` object
created by the `ComposeAndLog` infrastructure to allow the user to compose the message.

The `logcontext` object stores the "thread name" (prefix for log messages) and a copy of the `shared_ptr` to the `Worker` object
(and the initial timestamp -- in order to generate relative timestamps in the logs).
Once again, here is an example of the two `LogContext` objects (as created in the `main` function):

```
const auto t0 {Now ()};
const auto logcontext     {LogContext {t0}.SetSPWorker (Logger_spWorker).SetThreadName ("Main")};
const auto logcontextPlay {LogContext {t0}.SetSPWorker (Logger_spWorker).SetThreadName ("Play")};
```
